vich_uploader:
    db_driver: orm

    mappings:
        poster_file:
                uri_prefix: '%upload_directory%'
                upload_destination: '%kernel.project_dir%/public%upload_directory%'
                inject_on_load: true # injecte l'image au chargement du formulaire
                delete_on_update: false
                delete_on_remove: false
